{% set name = "recbole" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/recbole-{{ version }}.tar.gz
    sha256: 132a8a706462b26bed82d409b67fbc09e90b3a49b607c7ba76c2f1718d8ddc17
    patches:
      - patches/0001-update-colorlog-pinning.patch
  # use github release archive for tests
  - url: https://github.com/RUCAIBox/RecBole/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 1bc77a567083884b41ddd652b9b35078a0c3554c39ca38ab825ab2681eef138e
    folder: gh_src

build:
  number: 0
  # s390x: kmeans-pytorch (numba) unavailable
  # py>=312: ray unavailable
  # skip: True  # [py<38 or py>311 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pytorch >=1.10.0
    - numpy >=1.17.2
    - scipy >=1.6.0
    - pandas >=1.3.0
    - tqdm >=4.48.2
    # colorlog pinning relaxed to lower bound instead of exact
    # (we have more recent version and it seems to work).
    - colorlog >=4.7.2
    - colorama 0.4.4
    - scikit-learn >=0.23.2
    - pyyaml >=5.1.0
    - tensorboard >=2.5.0
    - thop >=0.1.1.post2207130030
    - tabulate >=0.8.10
    - plotly >=4.0.0
    - texttable >=0.9.0
    - psutil >=5.9.0
    - ray-core >=1.13.0,<=2.6.3
    # https://github.com/RUCAIBox/RecBole/blob/v1.2.0/.github/workflows/python-package.yml#L51
    - kmeans-pytorch
  run_constrained:
    - hyperopt 0.2.5

test:
  imports:
    - recbole
  requires:
    - pip
    - pytest
  source_files:
    - gh_src/run_recbole.py
    - gh_src/tests
  commands:
    - pip check
    - cd gh_src
    # https://github.com/RUCAIBox/RecBole/blob/v1.2.0/.github/workflows/python-package.yml#L55
    - python run_recbole.py --model=BPR --epochs=2
    # https://github.com/RUCAIBox/RecBole/blob/v1.2.0/run_test.sh#L7C1-L7C48
    - python -m pytest -v tests/config/test_config.py
    - python -m pytest -v tests/config/test_overall.py

about:
  home: https://recbole.io
  summary: A unified, comprehensive and efficient recommendation library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    RecBole is developed based on Python and PyTorch for reproducing and developing
    recommendation algorithms in a unified, comprehensive and efficient framework
    for research purpose. In the first version, our library includes 53 recommendation
    algorithms, covering four major categories: General Recommendation, Sequential
    Recommendation, Context-aware Recommendation and Knowledge-based Recommendation.
  doc_url: https://recbole.io/docs
  dev_url: https://github.com/RUCAIBox/RecBole

extra:
  recipe-maintainers:
    - lorepirri
