{% set name = "recbole" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/recbole-{{ version }}.tar.gz
    sha256: 132a8a706462b26bed82d409b67fbc09e90b3a49b607c7ba76c2f1718d8ddc17
    patches:
      - patches/0001-update-colorlog-pinning.patch
      - patches/0002-update-randomstate-to-default_rng-for-hyperopt.patch
  # use github release archive for tests
  - url: https://github.com/RUCAIBox/RecBole/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 1bc77a567083884b41ddd652b9b35078a0c3554c39ca38ab825ab2681eef138e
    folder: gh_src

build:
  number: 0
  # s390x: kmeans-pytorch (numba) unavailable
  # py>=312: ray unavailable
  skip: True  # [py<38 or py>311 or s390x]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - pytorch >=1.10.0
    - numpy >=1.17.2
    # Introduced upper pinning for scipy because of
    # https://github.com/RUCAIBox/RecBole/issues/2034
    # https://github.com/RUCAIBox/RecBole/issues/2090
    # similar to any other like
    # https://github.com/mmaelicke/scikit-gstat/issues/178
    # it can be removed when issues are closed.
    - scipy >=1.6.0,<1.13.0a0
    - pandas >=1.3.0
    - tqdm >=4.48.2
    # colorlog pinning relaxed to lower bound instead of exact
    # (we have more recent version and it seems to work).
    - colorlog >=4.7.2
    - colorama 0.4.4
    - scikit-learn >=0.23.2
    - pyyaml >=5.1.0
    - tensorboard >=2.5.0
    - thop >=0.1.1.post2207130030
    - tabulate >=0.8.10
    - plotly >=4.0.0
    - texttable >=0.9.0
    - psutil >=5.9.0
    # ray-tune is needed:
    # https://github.com/RUCAIBox/RecBole/blob/v1.2.0/recbole/quick_start/quick_start.py#L20
    # https://github.com/RUCAIBox/RecBole/blob/v1.2.0/conda/meta.yaml#L44
    - ray-tune >=1.13.0,<=2.6.3
  run_constrained:
    # originally ==0.2.5 adapted with a patch
    # to work with the more recent version we
    # have (0.2.7)
    - hyperopt >=0.2.5

# skip tests KGIN and MCCLK recommenders (they use
# torch-scatter, optional and unavailable)
{% set tests_to_skip = "test_kgin" %}
{% set tests_to_skip = tests_to_skip + " or test_mcclk" %}
# skip tests KGAT recommenders (they use dgl, optional and unavailable)
{% set tests_to_skip = tests_to_skip + " or test_kgat" %}
# faiss-cpu not available for some MKL issue for py 3.8 on osx-64
# https://github.com/AnacondaRecipes/faiss-split-feedstock/blob/main/recipe/meta.yaml#L112
# also, this problem occurs for osx-64 on "from . import _swigfaiss" then "_mkl_blas_caxpy"
# is not found:
# https://github.com/facebookresearch/faiss/issues/1755
# https://discourse.cmake.org/t/mkl-64lp-versus-64ilp-difficulties/1223
{% set tests_to_skip = tests_to_skip + " or test_NCL" %}  # [osx and x86_64]
{% set tests_to_skip = tests_to_skip + " or TestSequentialRecommender" %}  # [osx or (linux and aarch64)]


test:
  imports:
    - recbole
  requires:
    - pip
    - pytest
    - hyperopt
    # The following dependencies are specified in the CI
    # and they are optional.
    # We contacted the upstream authors and they seem optional:
    # https://github.com/RUCAIBox/RecBole/issues/2105#issuecomment-2559262386
    # Most of the recommenders are available optionally
    # except KGAT (missing 'dgl'), KGIN, and MCCLK (missing
    # 'torch-scatter').
    # https://github.com/RUCAIBox/RecBole/blob/v1.2.0/.github/workflows/python-package.yml#L36-L51
    - kmeans-pytorch
    - xgboost
    - lightgbm
    - faiss-cpu
    - networkx
    - protobuf #3.19.0
  source_files:
    - gh_src/run_recbole.py
    - gh_src/tests
  commands:
    - pip check
    - cd gh_src
    # Smoke test from the CI
    # https://github.com/RUCAIBox/RecBole/blob/v1.2.0/.github/workflows/python-package.yml#L55
    - python run_recbole.py --model=BPR --epochs=2
    # Tests run as specified in run_test.sh
    # https://github.com/RUCAIBox/RecBole/blob/v1.2.0/run_test.sh#L7C1-L7C48
    # "python -m pytest" is used instead of "pytest"
    # As suggested in
    # https://github.com/RUCAIBox/RecBole/blob/v1.2.0/.github/workflows/python-package.yml#L52
    - python -m pytest -vv tests/config/test_config.py
    - python -m pytest -vv tests/config/test_overall.py
    # config tests
    - python tests/config/test_command_line.py --use_gpu=False --valid_metric=Recall@10  --metrics="['Recall']" --epochs=200 --learning_rate=0.3
    # evaluation_setting tests
    - python -m pytest -vv tests/evaluation_setting
    # model tests
    - python -m pytest -vv tests/model/test_model_auto.py -k "not ({{ tests_to_skip }})"  
    # disabled: requires manual intervention
    # - python -m pytest -vv tests/model/test_model_manual.py
    # data tests
    - python -m pytest -vv tests/data/test_dataset.py
    - python -m pytest -vv tests/data/test_dataloader.py
    # hyper_tuning tests
    - python -m pytest -vv tests/hyper_tuning/test_hyper_tuning.py

about:
  home: https://recbole.io
  summary: A unified, comprehensive and efficient recommendation library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    RecBole is developed based on Python and PyTorch for reproducing and developing
    recommendation algorithms in a unified, comprehensive and efficient framework
    for research purpose. In the first version, our library includes 53 recommendation
    algorithms, covering four major categories: General Recommendation, Sequential
    Recommendation, Context-aware Recommendation and Knowledge-based Recommendation.
  doc_url: https://recbole.io/docs
  dev_url: https://github.com/RUCAIBox/RecBole

extra:
  recipe-maintainers:
    - lorepirri
